version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  win: circleci/windows@2.4.0

parameters:
  node-version:
    type: string
    default: '14.15.5'

variables:
  - &node-build-image
    - image: circleci/node:12.16.1-stretch

jobs:

  language-server:
    executor: win/default
    environment:
      NODE_VERSION: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: 'Install node'
          shell: bash.exe
          command: |
            echo 'nvm ls: '
            nvm ls
            nvm install $NODE_VERSION
            nvm use $NODE_VERSION
      - run:
          name: 'Install yarn'
          shell: bash.exe
          command: |
            npm install --global yarn
            yarn --version
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn
      - run:
          name: Build Packages
          shell: bash.exe
          command: |
            echo 'Building...'
            echo 'Node version: '
            node --version
            echo 'Node version: '
            yarn --version
            yarn run build
      - run:
          name: 'Run Unit Tests'
          shell: bash.exe
          command: |
            echo 'Run Unit Tests'
            mkdir -p ./test-results/junit
            JEST_JUNIT_OUTPUT_DIR=./test-results yarn run test:unit:coverage --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./test-results
      - run:
          name: Upload coverage report to Codecov
          shell: bash.exe
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

  notify_slack:
    docker: *node-build-image
    steps:
      - slack/notify:
          channel: web-tools-bot
          title: "Success: ${CIRCLE_USERNAME}'s commit-workflow"
          title_link: 'https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}'
          color: '#9bcd9b'
          message: "${CIRCLE_USERNAME}'s workflow <https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}|commit-workflow> in ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\n(${CIRCLE_BRANCH})"
          include_project_field: false
          include_visit_job_action: false
          include_job_number_field: false

workflows:
  version: 2
  commit-workflow:
    jobs:
      - language-server
      - notify_slack:
          requires:
            - language-server
